# Generated by Django 4.0.5 on 2022-06-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='architect',
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_location',
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='date_built',
        ),
        migrations.RemoveField(
            model_name='building',
            name='description',
        ),
        migrations.RemoveField(
            model_name='building',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='building',
            name='image_source',
        ),
        migrations.RemoveField(
            model_name='building',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='building',
            name='source_info',
        ),
        migrations.RemoveField(
            model_name='building',
            name='source_url',
        ),
    ]
